tests: Fix for Python 3.13 (unittest.makeSuite was removed)
```
ImportError while importing test module '…/pyftdi/pyftdi/tests/toolsimport.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
…/lib/python3.13/importlib/__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
pyftdi/tests/toolsimport.py:16: in <module>
    from unittest import TestCase, TestSuite, makeSuite, main as ut_main
E   ImportError: cannot import name 'makeSuite' from 'unittest' (…/lib/python3.13/unittest/__init__.py)
```

https://github.com/python/cpython/issues/104835
https://github.com/python/cpython/pull/104836
https://github.com/python/cpython/commit/b1cb30ec8639e4e65f62e8f6cd44e979640431c8
https://docs.python.org/3/whatsnew/3.13.html#unittest